apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- ../../base
namespace: prod
replicas:
- name: myapp
  count: 3
images:
- name: rokaa666/myapp
  newTag: v9.9.9-doesnotexist
commonLabels:
  environment: production
